src/components/common/ProfileCard.jsx, src/components/features/login/LoginForm.jsx, src/components/features/myPage/LoginSelect.jsx, src/components/features/myPage/UserProfileContainer.jsx, src/layout/layout.jsx
"Fix(ProfileCard.jsx : navigate추가 및 css조정중,
LoginForm.jsx : Css 수정,
LoginSelect.jsx : Css 수정, 
UserProfileContainer.jsx : 타인의 프로필 정렬외 기능 구현완료
,layout.jsx : width-> max-width 수정)"
=> Merge( revision : 70b6bba)

src/app/modules/commentsSlice.jsx, src/app/modules/detailSlice.jsx, src/app/modules/followSlice.jsx, src/app/modules/mbtiSlice.jsx, src/components/features/feedDetail/FeedDetailContainer.jsx, src/components/features/mbti/MbtiForm.jsx, src/components/features/myPage/myPageFollow.jsx, src/components/features/signUp/signUpForm.jsx, src/components/features/welcome/WelcomeForm.jsx
Fix(
commentsSlice.jsx,
detailSlice.jsx,
followSlice.jsx,
mbtiSlice.jsx,
MbtiForm.jsx,
myPageFollow.jsx,
signUpForm.jsx, 
WelcomeForm.jsx : 주석삭제, 
FeedDetailContainer.jsx : Ref 추가  )
=> Merge (revision : b61d4dd)

src/app/modules/mytodosSlice.jsx, src/app/modules/todolistsSlice.jsx, src/components/common/ChallengeCard.jsx, src/components/common/footer.jsx, src/components/common/header.jsx, src/components/features/feed/FeedPageContainer.jsx, src/components/features/selectMBTIFeed/SelectMBTIFeedContainer.jsx, src/components/features/setToDo/SetToDoContainer.jsx, src/layout/layout.jsx, src/router/router.jsx
- Fix
- ChallengeCard.jsx: 경로에 따라 변화되는 사항에 맞게 버튼이나 사이즈의 조정이 들어가도록 함, 진행중/완료 처리 관련 코드 추가
- footer.jsx: 경로에 따라 선택된 버튼의 색상이 출력되도록 변경
- header.jsx: console.log() 제거
- FeedPageContainer.jsx: mbti 선택 후에 진입 시, 선택한 mbti의 값이 받아지도록 연결함
- SelectMBTIFeedContainer.jsx: 피드 페이지 내 MBTI 선택 로직 구현 완료, 로그인/미로그인 시에 따른 버튼 색상 적용/미적용 처리 완료
- SetToDoContainer.jsx: 사용되지 않거나 불필요한 내용 제거
- layout.jsx: 페이지에 따라 달라져야하는 배경색상 코드 수정
- router.jsx: MBTI 경로에 따라 적용할 router 추가
=> Merge (revision: 7b42e0b)

src/app/modules/mytodosSlice.jsx, src/components/common/ChallengeCard.jsx, src/components/features/helpdesk/HelpDeskContainer.jsx, src/components/features/setToDo/SetToDoContainer.jsx, src/pages/helpDesk.jsx
- Fix
- helpDesk.jsx: 컨테이너 컴포넌트의 경로가 잘못된 문제 수정
- SetToDoContainer.jsx, SetToDoContainer.jsx: 선택 날짜와 현재 날짜 받아오는 변수 선언, 선택 날짜와 오늘 날짜 및 도전 선택 여부에 따라 나오는 컴포넌트가 다르게 적용되도록 수정, 사용하지 않는 스타일드 컴포넌트 변수 제거
- HelpDeskContainer.jsx: 컴포넌트의 경로가 잘못된 문제 수정
- mytodosSlice.jsx: initialState에 isCompleted key 추가, errorMessage가 제대로 받아와지지 않는 문제 수정, 내가 제안한 도전을 삭제해주는 deleteMyTodosFetch의 Creator와 Reducer 수정, 내가 해보기로 한 도전을 포기시켜주는 deleteSetUpTodoFetch의 Creator와 Reducer 수정
- ChallengeCard.jsx: 페이지와 내 상태에 따라 상세 메뉴 버튼을 출력시킬지 여부 관련 설정 로직 추가, 상세 메뉴 누를 시 출력되는 팝업창 기능 추가, 챌린지 진행중/완료 처리를 적용해주는   코드 추가, 오늘 도전하기 위해 등록한 미믹을 취소하거나 내가 제안한 미믹을 삭제할 수 있도록 코드 추가, 기타 추가된 스타일드 컴포넌트 변수 작성 진행)
=> Merge (revision: 200a51b)

src/app/modules/mytodosSlice.jsx, src/components/common/ChallengeCard.jsx, src/components/features/activity/ActivityContainer.jsx, src/components/features/myPage/MyPageContainer.jsx, src/components/features/setToDo/SetToDoContainer.jsx, src/components/interface/styledCommon.jsx, src/layout/layout.jsx, src/pages/activity.jsx
- Add
- ActivityContainer.jsx
- Fix
- mytodosSlice.jsx: 도전 Todo 포기 처리 시 date가 전달되지 않던 문제 수정
- ChallengeCard.jsx & layout.jsx: 경로 추가에 따른 완료 버튼 처리와 카드 사이즈 조정 및 화면 배경색 조정
- styledCommon.jsx: StCommonBorder 관련 width와 height 변수 처리 진행
- SetToDoContainer.jsx: 주석 일부 수정
- MyPageContainer.jsx: 더 이상 사용하지 않는 함수나 코드 및 주석 제거
- activity.jsx: ActivityContainer 컴포넌트 배치
=> Merge (revision: 9912d73)

src/components/common/ChallengeCard.jsx
- Fix
- ChallengeCard.jsx: 상세 메뉴 생성 조건 내에 내 데이터가 있는지를 체크하는 조건 추가
=> CDSP-112 미 로그인 상태에도 피드가 출력되지 않는 문제 / Merge (revision: 3d178ad)

src/app/modules/accountsSlice.jsx, src/app/modules/mytodosSlice.jsx, src/app/modules/todolistsSlice.jsx, src/components/common/ChallengeCard.jsx, src/components/features/selectMBTIFeed/SelectMBTIFeedContainer.jsx, src/components/features/withdraw/WithdrawContainer.jsx
- Fix
- accountsSlice.jsx & mytodosSlice.jsx & todolistsSlice.jsx: 문서 내로 API 통신 진행하여 사용하지 않는 Creator 및 Reducer 제거
- ChallengeCard.jsx & SelectMBTIFeedContainer.jsx & WithdrawContainer.jsx: 각각 사용하던 Slice에서 Creator 및 Redecer를 제거한 내용을 파일 내 함수에 직접적인 API 통신 로직으로 변경)
=> CDSP-114 API 리팩토링 - 프론트엔드 Merge(revision: 80e3361)

src/components/common/ChallengeCard.jsx, src/components/features/myPage/MyPageContainer.jsx, src/components/features/setToDo/SetToDoContainer.jsx, src/components/features/withdraw/WithdrawContainer.jsx, src/components/modifyProfile/ProfileModifyForm.jsx
- Fix
- MyPageContainer.jsx & SetToDoContainer.jsx: window.location.assign()을 navigate()로 변경
- WithdrawContainer.jsx & ProfileModifyForm.jsx & ChallengeCard.jsx: API통신 후 로직을 try-catch문으로 개선
=> Merge (revision: e9e4926)

src/components/features/feedDetail/FeedDetailContainer.jsx, src/components/features/follow/MyPageFollow.jsx, src/components/features/mbti/MbtiForm.jsx, src/components/features/signUp/SignUpForm.jsx
- Fix(
FeedDetailContainer.jsx,
MyPageFollow.jsx,
MbtiForm.jsx,
SignUpForm.jsx : try/catch 문으로 수정)
=> Merge (revision : fba86d7)

src/components/features/activity/ActivityContainer.jsx, src/components/features/setToDo/SetToDoContainer.jsx
- Fix
- ActivityContainer.jsx: map 메소드로 인해 데이터가 없어 페이지가 제대로 출력되지 않는 이슈 수정
- SetToDoContainer.jsx: 아직 작성하지 않거나, 작성되지 않은 내용이 있을 시 데이터의 공백으로 페이지 출력이 망가지는 이슈 수정
=> Merge (revision: 3163f78)

src/app/modules/mytodosSlice.jsx, src/app/modules/setUpTodoSlice.jsx, src/app/store.js, src/components/features/activity/ActivityContainer.jsx, src/components/features/setToDo/SetToDoContainer.jsx
- Add
- setUpTodoSlice.jsx
- Fix
- store.jsx: setUpTodoSlice 항목 추가
- mytodosSlice.jsx: setUpTodo 페이지에 사용하는 Creator 및 Reducer 이전으로 관련 내용 삭제
- ActivityContainer.jsx: 사용하지 않는 모듈 제거
- SetToDoContainer.jsx: slice 분리를 통한 데이터 get 방식 처리 변경
=> Merge (revision: 3e48491)

src/app/modules/instance.jsx
- Fix
- instance.jsx: 파일이 갱신되지 않아서 토큰 정보가 받아지지 않던 이슈 수정
=> Merge (revision: d32713a)

src/components/features/welcomePage/StartContainer.jsx, src/pages/welcomePage.jsx
- Add
- StartContainer.jsx
- Fix
- welcomePage.jsx: 첫 동작 시 출력될 페이지 관련 StartContainer.jsx 컴포넌트 추가
=> Merge (revision: 8acac41)

package-lock.json, package.json, src/app/modules/kakaoOauth.jsx, src/app/modules/todolistsSlice.jsx, src/components/common/ChallengeCard.jsx, src/components/features/feed/FeedPageContainer.jsx, src/components/features/login/LoginForm.jsx, src/components/features/myPage/LoginSelect.jsx, src/components/features/ohterPage/UserProfileContainer.jsx, src/components/features/todo/WriteTodoForm.jsx
Fix(package-lock.json,package.json : 무한스크롤 구현을 위한 라이브러리 react-intersection-observer설치,
kakaoOauth.jsx : 카카오 로그인 예시페이지 사용x중,
todolistsSlice.jsx : 주석 처리 추가,
ChallengeCard.jsx : 다른 브래치에서 추가됨,
FeedPageContainer.jsx : 무한 스크롤 추가 테스트중 ,
LoginForm.jsx : navigate로 변경,
LoginSelect.jsx  : css수정,
UserProfileContainer.jsx : css 수정 , 
WriteTodoForm.jsx : navigate로 변경)"
=> Merge ( revision : 215c6c4)

src/components/features/welcomePage/StartContainer.jsx, src/router/router.jsx
- Fix
- StartContainer.jsx: 웰컴 페이지 관련 내용 구현
- router.jsx: 토큰 상태에 따라 메인 페이지와 웰컴 페이지 출력 여부를 결정하는 로직 추가
=> Merge (revision: 72ea8e6)

src/components/features/feedDetail/FeedDetailContainer.jsx
-Fix  (
FeedDetailContainer.jsx : API 수정부분, 적용완료 )
=> Merge (revision : be722e5)

src/app/modules/todolistsSlice.jsx, src/components/features/feed/FeedPageContainer.jsx
92e1f1b -> Fix(todolistsSlice.jsx,FeedPageContainer.jsx: mbti 선택 가능 및 무한스크롤 수정중)
71859ce=> Fix(todolistsSlice.jsx : axios -> preInstance,instance로 수정,
FeedPageContainer.jsx : 무한스크롤 x시 : (로그인/미로그인)<->(최신순/도전순/댓글순)<->(MBTI선택/미선택) 연결 완료 무한스크롤 : 렌더링이슈가 너무 많이나와서 잠정중단
=> Merge( revision : 92e1f1b ~ 71859ce)

src/components/common/ProfileCard.jsx, src/components/features/login/LoginForm.jsx, src/components/features/todo/WriteTodoForm.jsx
Fix(ProfileCard.jsx : 디자인 변경에 따른 CSS 수정,
LoginForm.jsx,WriteTodoForm.jsx : 주석 정리 및 설명 추가 , CSS 수정) #85"
=> Merge (revision : 8e073ba)

src/components/common/ChallengeCard.jsx, src/components/features/feedDetail/DetailCard.jsx, src/components/features/main/MainContainer.jsx, src/components/features/setToDo/SetToDoContainer.jsx, src/components/features/welcomePage/StartContainer.jsx, src/utils/commonFunc.jsx
- Add
- commonFunc.jsx
- DetailCard.jsx
- Fix 
- ChallengeCard.jsx: 금일 날짜 불러오는 함수 타 파일로 분리
- DetailCard.jsx 추가로 인한 일부 조건 제거
- SetToDoContainer.jsx: 프로필 영역의 margin이 어색한 문제 수정
- StartContainer.jsx: 시작 페이지에 Navigation 추가
=> Merge (revision: c8fc639)

src/app/modules/todolistsSlice.jsx, src/components/features/feed/FeedPageContainer.jsx
Fix(todolistsSlice.jsx : 렌더링 이슈 해결하기 위한 콘솔 추가 안정화 될 때 콘솔삭제해야함,
FeedPageContainer.jsx : 최신순,도전순,댓글순 동작 시 새로고침되는 현상 e.preventDefault()로 해결, 간헐적으로 mbti 도전 눌렀을 때 전체 카드가 랜더링되는 이슈 임시로 해결(완전하게 해결되지는 않은 것 같음) #85
=> Merge(revision :34e4119)

src/components/features/feedDetail/FeedDetailContainer.jsx, src/components/features/signUp/SignUpForm.jsx
Fix (CSS 수정 :  FeedDetailContainer.jsx, SignUpForm.jsx)
=> Merge (revision : 719f410)

src/components/features/feedDetail/FeedDetailContainer.jsx
- Fix
- FeedDetailContainer.jsx: 상세 피드 관련 출력 카드 컴포넌트 변경
=> Merge (revision: a61a00e)

src/components/common/ProfileCard.jsx, src/components/features/feed/FeedPageContainer.jsx
Fix(ProfileCard.jsx : 닉네임 왼쪽에서 나타나게 변경, 
FeedPageContainer.jsx : 버튼 선택하기 반응형이 아니라 고정값으로 변경 및 색상변경)
=> Merge(revision : 6932a05)

package-lock.json, package.json, src/components/features/feedDetail/FeedDetailContainer.jsx, src/components/features/follow/MyPageFollow.jsx
- Fix(
FeedDetailContainer.jsx, MyPageFollow.jsx :  CSS 수정 버튼 간격조정 )
=> Merge (revision : e164ffe)

src/components/common/ProfileCard.jsx, src/components/features/follow/MyPageFollow.jsx, src/components/features/signUp/SignUpForm.jsx
-Fix ( 
ProfileCard.jsx : navigate 에 state값 추가 - boolean값 보내주기위함 , 
follow/MyPageFollow.jsx : css 수정-검색창+팔로우/팔로잉선택창, useLocation의 사용-state값 받아오기 , 
SignUpForm.jsx : 불필요 주석 삭제 )
=> Merge (revision : 0f03fe5)

src/components/features/feedDetail/FeedDetailContainer.jsx, src/components/features/follow/MyPageFollow.jsx
-Fix (
FeedDetailContainer.jsx :  useEffect 의존성 배열 추가 , 
MyPageFollow.jsx :  css - scroll 삭제 )
=> Merge (revision : 19f9132)

src/components/features/feedDetail/FeedDetailContainer.jsx
-Fix ( 
FeedDetailContainer.jsx : 
본인이 만든 피드 선택시 팔로우버튼 안보이도록 수정 - myToken 과 detailState 의 userId 값 비교) #84
=> Merge (revision : c438d84)

src/components/features/feedDetail/FeedDetailContainer.jsx
-Fix (
FeedDetailContainer.jsx : css 수정, mbti 뷰 추가 )
=> Merge (revision : 7581aef)

src/components/features/activity/ActivityContainer.jsx, src/components/features/ohterPage/OthersCard.jsx, src/components/features/ohterPage/UserProfileContainer.jsx
- Add
- OthersCard.jsx
- Fix
- ActivityContainer.jsx: 정렬 버튼 누를 시에 출력되는 버튼 색상 변경 적용
- UserProfileContainer.jsx: 유저 페이지 전용 카드 분리 적용
=> Merge (revision: c7832c1)

src/components/features/setToDo/SetToDoContainer.jsx, src/components/features/setToDo/SetUpToDoCard.jsx, src/layout/layout.jsx
- Fix
- SetToDoContainer.jsx: 달력 월 전환 버튼 위치 및 상단 padding 조정
- SetUpToDoCard.jsx: border 내용이 적용되지 않던 이슈 수정
- layout.jsx: 디자인에 따른 일부 경로 배경 적용 사항 제거 #82
=> Merge (revision: c6e2d07~560a4a6) 

src/components/features/follow/MyPageFollow.jsx
- Fix (
MyPageFollow.jsx : 팔로우/팔로잉 검색 기능 추가 )
=> Merge (revision : 6f903d6)

src/components/features/follow/MyPageFollow.jsx
- Fix (
MyPageFollow.jsx : 본인의 팔로우페이지가 아니면 팔로잉 삭제버튼 안나오게 수정 )
=> Merge (revision : 20496ba)

src/components/common/ProfileCard.jsx, src/components/features/feed/FeedPageContainer.jsx, src/components/features/ohterPage/UserProfileContainer.jsx, src/components/features/todo/WriteTodoForm.jsx
- ProfileCard.jsx : 모바일 크기 css추가 및 팔로우 팔로잉 네비게이트 할때 전달해주는 state값 변경
- FeedPageContainer.jsx : 모바일 크기 css 추가
- UserProfileContainer.jsx : ProfileCard.jsx 컴포넌트를 불러와서 적용함에 따라 변경되는 css부분 수정
- WriteTodoForm.jsx : 모바일 크기 css추가 및 미믹 작성할 때 오류가 발생하면 에러 alert추가
=> Merge ( revision : 9ae9fec ) 

src/components/features/feedDetail/FeedDetailContainer.jsx, src/components/features/follow/MyPageFollow.jsx, src/components/features/signUp/SignUpForm.jsx
-Fix (
FeedDetailContainer.jsx : 댓글 삭제버튼 아이콘변경 & 모달창에서 삭제하기 , 
MyPageFollow.jsx : 팔로우/팔로잉 네비게이션state값 수정, 
SignUpForm.jsx :  css 수정 ) #95
=> Merge (revision : deea595 )

src/components/common/ProfileCard.jsx, src/components/features/ohterPage/UserProfileContainer.jsx, src/components/features/todo/WriteTodoForm.jsx
-ProfileCard.jsx : 페이지 경로에 따른 카드 구성 수정 및 css 수정 중 otherspage의 경우 팔로우/언팔로우 기능 추가
-UserProfileContainer.jsx : 프로필 카드 컴포넌트 수정에 따른 css변경
-WriteTodoForm.jsx : 알럿 내용 변경
=> Merge ( revision : 8dfc574 )

src/components/features/feedDetail/FeedDetailContainer.jsx
Fix ( FeedDetailContainer.jsx : css 프로필 이미지 수정 )
=> Merge (revision : 42ece8c)

src/components/common/ChallengeCard.jsx, src/components/common/ProfileCard.jsx, src/components/features/changePW/ChangePWContainer.jsx, src/components/features/myPage/MyPageContainer.jsx, src/components/features/ohterPage/OthersCard.jsx, src/components/features/setToDo/SetToDoContainer.jsx, src/components/modifyProfile/ProfileModifyForm.jsx
- Fix
- ChallengeCard.jsx: 카드 간의 margin 간격 조정 #95
- ProfileCard.jsx: 궁합 알아보기 누를 시 출력될 모달창 적용
- ChangePWContainer.jsx: 비밀번호 변경 시, 안내 문구에 9글자 이상 작성하라고 노출되는 문제 수정 #121
- MyPageContainer.jsx: 궁합 알아보기 버튼 위치 이동에 따른 컴포넌트 제거 및 프로필 영역 margin 조정
- OthersCard.jsx: 나와 타인의 프로필 페이지에서 정렬 기능이 있음에도 댓글 수와 미믹 도전 수가 출력되지 않는 문제 수정 #124, 피드 미믹 누를 시에 상세 미믹 페이지로 이동되지 않는 문제 수정 #125
- SetToDoContainer.jsx: 프로필 카드 영역 수정에 따른 margin값 수정 #95
- ProfileModifyForm.jsx: 페이지 진입 시, 토큰 통해서 이미지 정보를 받아와 이미지 영역에 출력되도록 수정
=> Merge (revision: b9ad095)

src/components/common/InputCard.jsx, src/components/features/feed/FeedPageContainer.jsx, src/components/features/login/LoginForm.jsx
Add
- InputCard.jsx : 로그인,회원가입 페이지에서 공통적으로 사용되는 input을 컴포넌트화 시켜서 사용하기위해 생성(보류중) 
Fix
- FeedPageContainer.jsx : 변수명 변경 및 디자인 시안에 따른 (도전완료, 정렬)라인 css수정
- LoginForm.jsx : InputCard.jsx 를 활용하기 위해 시도중 #117 (8dfc574) #118 (8dfc574)  #127(9ae9fec) 전에 커밋 못했습니다.
=> Merge ( revision : c93b875 )

README.md, src/components/common/ProfileCard.jsx, src/components/features/changePW/ChangePWContainer.jsx, src/components/features/setToDo/SetToDoContainer.jsx, src/components/features/setToDo/SetUpToDoCard.jsx, src/components/modifyProfile/ProfileModifyForm.jsx, src/utils/loadingState.jsx
- Add
- loadingState.jsx
- Fix
- READMD.md: 파일 경로 전체 수정
- ProfileCard.jsx: 프로필에 이미지 없을 시에 placeholder 이미지가 출력되지 않는 이슈 수정
- SetToDoContainer.jsx: 로딩 화면 추가에 따른 로딩 로직 추가
- SetToDoCard.jsx: 로딩 화면 추가에 따른 로딩 로직 추가
- ProfileModifyForm.jsx: 로딩 화면 추가에 따른 로딩 로직 추가
=> Merge (revision: 5e7c2d9)

src/components/features/feedDetail/FeedDetailContainer.jsx
Fix ( FeedDetailContainer.jsx : 파싱 오류 수정)
=> Merge (revision : 816fbd3)

src/components/common/ProfileCard.jsx, src/components/features/follow/MyPageFollow.jsx
- Fix (
ProfileCard.jsx : navigate - state 수정, 
MyPageFollow.jsx : css - 검색아이콘 위치조정 외 검색, 팔로잉창 색상 수정 )
=> Merge (revision : 79aa012)

src/components/features/feedDetail/FeedDetailContainer.jsx, src/components/features/follow/MyPageFollow.jsx, src/components/features/mbti/MbtiForm.jsx, src/components/features/ohterPage/UserProfileContainer.jsx
- Fix
- UserProfileContainer.jsx: 탈퇴한 회원일 경우, 탈퇴한 회원의 닉네임을 눌렀을 때 아무런 alert 없이 상세 페이지로 넘어가지는 문제 수정 #141
- MbtiForm.jsx: 카카오톡으로 최초 로그인 시, 프로필 변경을 하려는데 MBTI 선택이 안되는 문제 수정 #142
- FeedDetailContainer.jsx & MyPageFollow.jsx: 프로필 이미지가 제대로 출력되지 않던 이슈 수정 #143
=> Merge (revision: 60b5951~39c5613)

src/components/features/signUp/SignUpForm.jsx
Fix ( SignUpForm.jsx : css 회원가입 버튼 수정 )
=> Merge (revision : f7b9c4d)

src/components/features/follow/MyPageFollow.jsx, src/components/features/signUp/SignUpForm.jsx, src/components/features/test/TestForm.jsx, src/pages/testPage.jsx, src/router/router.jsx
- Fix ( 
MyPageFollow.jsx : css - 모바일사이즈 추가, 
SignUpForm.jsx : css - 모바일사이즈 추가, 
router.jsx : navigate - /test 추가) 
- Add ( 
testPage.jsx & TestForm.jsx : 심리테스트 컴포넌트 생성 )
=> Merge (revision : 8bed46b)

src/components/features/feedDetail/FeedDetailContainer.jsx, src/components/features/mbti/MbtiForm.jsx, src/components/interface/styledCommon.jsx
- Fix ( 
FeedDetailContainer.jsx : css - 모바일사이즈 적용, 
MbtiForm.jsx : css -모바일사이즈 적용 ,
styledCommon.jsx : StShadowBackgroundDiv - 모바일사이즈 적용)
=> Merge (revision : 314b0a3)

public/index.html, src/app/modules/mainSlice.jsx, src/app/store.js, src/components/common/ChallengeCard.jsx, src/components/features/feedDetail/DetailCard.jsx, src/components/features/main/MainContainer.jsx, src/components/features/modifyProfile/ProfileModifyForm.jsx, src/components/features/myPage/MyPageContainer.jsx, src/utils/token.jsx
- Add
- mainSlice.jsx
- 
- Fix
- index.html: twitter 관련 meta 태그 추가
- store.js: main에 사용할 Slice Reducer 추가
- ChallengeCard.jsx: 토큰 없을 시 로그인 페이지로 보내도록 로직 수정, 모바일 환경에 맞는 사이즈 적용
- DetailCard.jsx: 모바일 환경에 맞는 사이즈 적용
- MainContainer.jsx: 메인 페이지 슬라이스 변경, Slice 관련 사항 적용
- ProfileModifyForm.jsx: JPG 확장명 대문자로 있는 사항 포함함.
- MyPageContainer.jsx: 향후 업데이트 사항 비공개 처리
- token.jsx: 토큰 확인 로직 내 토큰이 없을 시 null 값 반환 처리함.
=> Merge (revision: 4cee3de)

src/components/common/header.jsx
- Fix
- header.jsx: 상세 페이지 내 헤더 이미지가 출력되지 않는 이슈 수정
=> Merge (revision: aaf3160~0d44ad0)

public/index.html, src/components/features/main/MainContainer.jsx, src/utils/token.jsx
- Fix
- index.html: Google Analytic 배치 적용
- MainContainer.jsx: 배너 링크 배치, 토큰 데이터 체크 로직 수정
- token.jsx: 토큰 정보 확인 함수 내용 수정
=> Merge (revision: 5a7dc95)

src/components/common/ChallengeCard.jsx, src/components/common/ProfileCard.jsx, src/components/common/footer.jsx, src/components/features/changePW/ChangePWContainer.jsx, src/components/features/feed/FeedPageContainer.jsx, src/components/features/feedDetail/FeedDetailContainer.jsx, src/components/features/helpdesk/FQAAccordionCard.jsx, src/components/features/helpdesk/HelpDeskContainer.jsx, src/components/features/helpdesk/NoticeAccordionCard.jsx, src/components/features/login/LoginForm.jsx, src/components/features/main/MainContainer.jsx, src/components/features/mbti/MbtiForm.jsx, src/components/features/modifyProfile/ProfileModifyForm.jsx, src/components/features/myPage/LoginSelect.jsx, src/components/features/myPage/MyPageContainer.jsx, src/components/features/ohterPage/OthersCard.jsx, src/components/features/selectMBTIFeed/SelectMBTIFeedContainer.jsx, src/components/features/setToDo/SetToDoContainer.jsx, src/components/features/setToDo/SetUpToDoCard.jsx, src/components/features/signUp/SignUpForm.jsx, src/components/features/todo/WriteTodoForm.jsx, src/components/features/welcomePage/StartContainer.jsx, src/components/features/withdraw/WithdrawContainer.jsx
- Fix
- ChallengeCard.jsx & ProfileCard.jsx & ChangePWContainer.jsx & FeedPageContainer.jsx & FeedDetailContainer.jsx & FQAAccordionCard.jsx & HelpDeskContainer.jsx & NoticeAccodionCard.jsx & MbtiForm.jsx & ProfileModifyForm.jsx & LoginSelect.jsx & OthersCard.jsx & SelectMBTIFeedContainer.jsx & SetToDoContainer.jsx & WriteTodoForm.jsx & WithdrawContainer.jsx: hover transition 추가,
- SetUpToDoCard.jsx: 진행중/완료 버튼 적용이 되지 않는 문제 수정 #153
- SignUpForm.jsx: hover transition 추가, 버튼 및 input 너비가 맞지 않던 이슈 수정
- Footer.jsx: 모바일 화면에서의 메뉴 갭 수정
- MyPageContainer.jsx: hover transition 추가, hover 추가에 따른 메뉴 padding/margin 조정
=> Merge (revision: 60034ca~457c9ca)

src/components/common/ProfileCard.jsx, src/components/features/activity/ActivityContainer.jsx, src/components/features/changePW/ChangePWContainer.jsx, src/components/features/feed/FeedPageContainer.jsx, src/components/features/helpdesk/FQAAccordionCard.jsx, src/components/features/helpdesk/HelpDeskContainer.jsx, src/components/features/helpdesk/NoticeAccordionCard.jsx, src/components/features/main/MainContainer.jsx, src/components/features/modifyProfile/ProfileModifyForm.jsx, src/components/features/myPage/MyPageContainer.jsx, src/components/features/ohterPage/OthersCard.jsx, src/components/features/selectMBTIFeed/SelectMBTIFeedContainer.jsx, src/components/features/signUp/SignUpForm.jsx, src/components/features/welcomePage/StartContainer.jsx, src/components/features/withdraw/WithdrawContainer.jsx
- Fix
- router.jsx: Layout 컴포넌트를 위치 변경
- WithdrawContainer.jsx & StartContainer.jsx & SelectMBTIFeedContainer.jsx & OthersCard.jsx & ProfileModifyForm.jsx & MyPageContainer.jsx & NoticeAccordionCard.jsx & HelpDeskContainer.jsx & FQAAccordionCard.jsx & FeedPageContainer.jsx & ChangePWContainer.jsx & ActivityContainer.jsx & MainContainer.jsx & ProfileCard.jsx & SignUpForm.jsx : 모바일 사이즈에 맞춘 CSS 수정 진행
=> Merge (revision: 7532c97)

src/components/common/ProfileCard.jsx, src/components/features/feed/FeedPageContainer.jsx, src/components/features/ohterPage/UserProfileContainer.jsx
Fix
-ProfieCard.jsx, FeedPageContainer.jsx, UserProfileContainer.jsx : 웹 및 모바일 CSS수정
=> Merge ( revision : 27336c2 )

src/components/features/feedDetail/DetailCard.jsx, src/components/features/setToDo/SetToDoContainer.jsx, src/components/features/setToDo/SetUpToDoCard.jsx
- Fix
- DetailCard.jsx & SetToDoContainer.jsx & SetUpToDoCard.jsx: 모바일 사이즈를 고려한 CSS 조정 진행
=> Merge (revision: 925e94a~5713d1a)

src/components/features/feed/FeedPageContainer.jsx
- FeedPageContainer.jsx : 중복 렌더링 수정 , 로딩 적용(수정필요),
=> Merge ( revision : 29bd890 )

src/components/features/feedDetail/FeedDetailContainer.jsx, src/components/features/follow/MyPageFollow.jsx, src/components/features/signUp/SignUpForm.jsx
- Fix (
FeedDetailContainer.jsx : css - 프로필박스 내부 위치 수정, 
MyPageFollow.jsx : css - 폰트, 위치 수정 , 
SignUpForm.jsx : 닉네임 12글자허용으로 수정 )
=> Merge( revision : a9576a5 )

src/components/features/feed/FeedPageContainer.jsx, src/components/features/ohterPage/UserProfileContainer.jsx
741b008 
- FeedPageContainer.jsx : 사전 배포 전 검색 관련 기능 주석 전커밋에서 넣지 못했던 이슈번호 추가 
61d50e6
- FeedPageContainer.jsx : 정렬 버튼 클릭 후 바깥 쪽 검은 화면 여백 수정 및 mbti 선택 후 정렬 이슈 수정
- UserProfileContainer.jsx :  정렬 버튼 클릭 후 바깥 쪽 검은 화면 여백 수정
=> Merge ( revision : 61d50e6 ~ 741b008 )

src/components/features/feed/FeedPageContainer.jsx
- FeedPageContainer.jsx : 피드 페이지 진입시 로딩화면 구성
=> Merge ( revision : 5d571d6 )

src/components/common/ProfileCard.jsx, src/components/features/feed/FeedPageContainer.jsx, src/components/features/ohterPage/UserProfileContainer.jsx
Fix
-UserProfileContainer.jsx :  다른유저의 도전한 TO DO  및 제안한 TO DO  이름 변경 및  모바일 환경에서 터치 시 파란색 박스 나오지 않게 수정
-ProfileCard.jsx,FeedPageContainer.jsx : 모바일 환경에서 터치 시 파란색 박스 나오지 않게 수정
=> Merge( revision : c020c31 ) 

src/components/features/feedDetail/FeedDetailContainer.jsx, src/components/features/follow/MyPageFollow.jsx, src/components/features/signUp/SignUpForm.jsx
- Fix (
css 수정 - 모바일환경 버튼 클릭시 박스윤곽 보이는 에러 수정
FeedDetailContainer.jsx  /MyPageFollow.jsx : css  /SignUpForm.jsx : css )
=> Merge (revision : 0963096)

src/components/features/mbti/MbtiForm.jsx, src/pages/main.jsx, src/router/router.jsx
- Fix
- MbtiForm.jsx & main.jsx & router.jsx: 카카오 로그인 시 mbti 설정을 하지 않아도 메인화면으로 가버리는 문제 수정
=> Merge (revision: 778017b)

src/app/modules/todolistsSlice.jsx, src/components/features/mbti/MbtiForm.jsx, src/components/features/selectMBTIFeed/SelectMBTIFeedContainer.jsx
- Fix
- SelectMBTIFeedContainer.jsx & todolistsSlice.jsx: 로그아웃 후에도 MBTI 설정이 남아 있어 선택 화면에서 여전이 버튼에 색상이 출력되는 문제 수정
- MbtiForm.jsx: 로컬 로그인 시, MBTI 선택 페이지로 넘어가지 않는 문제 수정
=> Merge (revision: 8bda3f4~a3916a1)

src/components/features/feedDetail/FeedDetailContainer.jsx, src/components/features/test/TestForm.jsx
- Fix (
FeedDetailContainer.jsx : 로딩후 이전 페이지 보여지는 이슈 해결 - aysnc 사용 , 
TestForm.jsx : state 변환까지 수정 )
=> Merge (revision : a4cd67b)

src/components/features/feedDetail/FeedDetailContainer.jsx
- Fix
- FeedDetailContainer.jsx: 이미지 로딩 이슈를 고려하여 댓글 이미지를 토큰이 아닌 api를 통해 받아오는 이미지로 수정
=> Merge (revision: 9ae953c)

src/components/features/feedDetail/FeedDetailContainer.jsx
- Fix
- FeedDetailContainer.jsx: 댓글을 삭제하려고 했으나 라우터 이슈가 발생하여 삭제가 안되는 문제 수정 #181
=> Merge (revision: 8898a29)

src/components/features/feed/FeedPageContainer.jsx
- FeedPageContainer.jsx : 전체 피드조회에서 mbti 선택 버튼때문에 맨 아래 카드가 나타나지 않는 상황 수정
=> Merge ( revision : 01a8b8d )

src/components/features/feedDetail/FeedDetailContainer.jsx
- Fix (
FeedDetailContainer.jsx : 모바일에서 댓글삭제토글이 화면 밑으로 밀리는 현상 수정 )
=> Merge (revision : f474838)

src/components/features/feedDetail/FeedDetailContainer.jsx, src/components/features/mbti/MbtiForm.jsx, src/components/features/signUp/SignUpForm.jsx
- Fix ( 
FeedDetailContainer.jsx : 댓글수 160자미만 - maxlength추가, 
SignUpForm.jsx… : 닉네임 12글자이하로 변경, 
MbtiForm.jsx  : mbti버튼 미선택시 기존-서버오류메세지 출력되는것을 , 작성된  alert메세지로  변경  )
=> Merge (revision : 8a74780)

public/index.html, src/components/features/main/MainContainer.jsx, src/components/features/main/WelcomeForm.jsx, src/components/features/mbti/MbtiForm.jsx, src/components/features/welcomePage/StartContainer.jsx, src/pages/welcomePage.jsx, src/router/router.jsx
- Fix
- index.html: 사이트 언어가 영어로 설정되어 지속적으로 크롬 번역 확인창이 출력되는 문제/ lang="us"->"kr"로 변경 #199
- MainContainer.jsx & WelcomeForm.jsx & MbtiForm.jsx & StartContainer.jsx & welcomePage.jsx & router.jsx: 카카오톡 인앱 페이지에서 튜토리얼 페이지를 보고 메인 페이지에 진입하는데 로그인 후 다시 튜토리얼 페이지로 돌아가는 문제 수정 / 쿠키가 아닌 localStorage로 변경 #199
=> Merge (revision: ef77315)

src/components/common/ChallengeCard.jsx, src/components/common/ProfileCard.jsx, src/components/features/activity/ActivityContainer.jsx, src/components/features/feed/FeedPageContainer.jsx, src/components/features/feedDetail/DetailCard.jsx, src/components/features/feedDetail/FeedDetailContainer.jsx, src/components/features/helpdesk/HelpDeskContainer.jsx, src/components/features/main/WelcomeForm.jsx, src/components/features/myPage/MyPageContainer.jsx, src/components/features/ohterPage/OthersCard.jsx, src/components/features/ohterPage/UserProfileContainer.jsx, src/components/features/selectMBTIFeed/SelectMBTIFeedContainer.jsx, src/components/features/setToDo/SetUpToDoCard.jsx, src/components/features/withdraw/WithdrawContainer.jsx, src/components/interface/styledCommon.jsx, src/pages/myPage.jsx
- Fix
- 튜토리얼 페이지를 보고 메인 페이지에 진입하는데 로그인 후 다시 튜토리얼 페이지로 돌아가는 문제 수정 / 로그아웃, 회원탈퇴 시 온보딩 페이지 발생하는 이슈 수정 #199
- myPage.jsx: 마이 페이지를 누르면 로그인 상태인데 로그인 할 수 있는 창이 잠깐 나왔다 꺼지는 문제 수정 #202
- ActivityContainer.jsx: 나의 활동 페이지에 로딩화면이 메시지로 출력되는 문제 수정#201, 팝업 기능 출력 시, 외부 영역 눌러도 닫히지 않는 문제 수정 #203
- ProfileCard.jsx & ChallengeCard.jsx & FeedPageContainer.jsx & DetailCard.jsx & FeedDetailContainer.jsx & WelcomeForm.jsx & OthersCard.jsx & UserProfileContainer.jsx & SelectMBTIFeedContainer.jsx & SetUpToDoCard.jsx & styledCommon.jsx: #203
- HelpDeskContainer.jsx: 큐앤에이 더보기 버튼을 눌렀을때 작동이 안되는 문제 수정 #204
=> Merge (revision: 30fdf9f~ae83e5a)

src/components/common/footer.jsx, src/components/features/feedDetail/FeedDetailContainer.jsx, src/components/features/follow/MyPageFollow.jsx, src/components/features/todo/WriteTodoForm.jsx
- Fix
- FeedDetailContainer.jsx: 피드 상세페이지 댓글 작성에서 스페이스만 입력 후 작성버튼을 눌렀을 때 나타나는 문제 https://github.com/hanghae99-s8realweek-E3/frontend/issues/195
- WriteTodoForm.jsx 제안 페이지에서 글이 안 써지고 마지막 글자에서 계속 뱅뱅 도는 문제 수정 https://github.com/hanghae99-s8realweek-E3/frontend/issues/208
- footer.jsx: 마이페이지 팔로잉 리스트를 들어가면 하단 메뉴바에 피드 버튼이 활성화되는 문제 수정 https://github.com/hanghae99-s8realweek-E3/frontend/issues/206
- MyPageFollow.jsx: 팔로워 검색 시, 없는 값을 입력하면 팔로우/팔로워 리스트 전체가 노출되는 문제 수정 https://github.com/hanghae99-s8realweek-E3/frontend/issues/207
=> Merge (revision: 739ac7a~2f00470)

README.md
=> Merge (revision: d46ace2)

README.md
=> Merge (revision: 57496c5)

src/app/modules/todolistsSlice.jsx, src/components/common/header.jsx, src/components/features/follow/MyPageFollow.jsx, src/components/features/mbti/MbtiForm.jsx, src/components/features/selectMBTIFeed/SelectMBTIFeedContainer.jsx, src/components/features/signUp/SignUpForm.jsx, src/pages/mbti.jsx
- Fix
- header.jsx & mbti.jsx: MBTI 화면에서 뒤로 가기 버튼이나 mbti 페이지가 출력되는 이슈 수정
- MbtiForm.jsx: 카카오톡 약관을 취소할 경우에도 MBTI 선택을 진행할 수 있는 문제 수정 #212
- MyPageFollow.jsx: 팔로잉 쪽에서는 없는 값을 검색해도 모두 다 내용이 뜨는 문제 수정 #207
- todolistsSlice.jsx: 사용하지 않는 모듈 제거
- SelectMBTIFeedContainer.jsx: 선택한 MBTI 필터를 다시 해제할 수 없는 문제 수정 #213
- SignUpForm.jsx: 회원가입 버튼 누를 시 로딩이 발생하지 않는 문제 수정 #214
=> Merge (revision: bf05d43)

src/app/modules/followSlice.jsx, src/app/modules/todolistsSlice.jsx, src/components/common/ProfileCard.jsx, src/components/features/changePW/ChangePWContainer.jsx, src/components/features/feedDetail/DetailCard.jsx, src/components/features/feedDetail/FeedDetailContainer.jsx, src/components/features/follow/MyPageFollow.jsx, src/components/features/mbti/MbtiForm.jsx, src/components/features/modifyProfile/ProfileModifyForm.jsx, src/components/features/ohterPage/OthersCard.jsx, src/components/features/selectMBTIFeed/SelectMBTIFeedContainer.jsx, src/components/features/setToDo/SetUpToDoCard.jsx, src/components/features/signUp/SignUpForm.jsx, src/components/features/todo/WriteTodoForm.jsx, src/components/features/withdraw/WithdrawContainer.jsx
- Fix
- MbitForm.jsx: MBTI 선택 화면에서 MBTI란? 버튼 누를 시 아무런 동작이 발생하지 않는 문제 수정 #216
- SelectMBTIFeedContainer.jsx: 도움말 아이콘 관련 CSS 수정, 에러 발생 시, alert 메세지가 서버 메시지로 나오는 문제 수정 #196
- followSlice.jsx & todolistsSlice.jsx & ProfileCard.jsx & ChangePWContainer.jsx & DetailCard.jsx & FeedDetailContainer.jsx & MyPageFollow.jsx & ProfileModifyForm.jsx & OthersCard.jsx & SetUpToDoCard.jsx & SignUpForm.jsx & WriteTodoForm.jsx & WithdrawContainer.jsx: 에러 발생 시, alert 메세지가 서버 메시지로 나오는 문제 수정 #196
=> Merge (revision: 43f7688)

src/components/features/feedDetail/FeedDetailContainer.jsx, src/components/features/follow/MyPageFollow.jsx, src/components/features/modifyProfile/ProfileModifyForm.jsx, src/components/features/signUp/SignUpForm.jsx, src/components/features/todo/WriteTodoForm.jsx
- Fix
- ProfileModifyForm.jsx: 공백 닉네임이나 공백 미믹, 공백 댓글 입력이 가능한 문제, 회원정보 수정에서 정보가 변하지 않았음에도 변경이 완료됐다고 나오는 문제, 프로필 변경 화면에서 나의 정보를 0자 또는 12자 이상 입력 시 오류처리가 되지 않는 문제 수정 #220 #221 #218
- FeedDetailContainer.jsx: 도전할래요!를 눌러 상태가 변경될 시, 이후 버튼이 비활성화되지 않는 문제, 공백 닉네임이나 공백 미믹, 공백 댓글 입력이 가능한 문제 수정 #219 #221
- MyPageFollow.jsx: 유저 팔로우 / 팔로우 페이지에서 유저의 이미지 부분 클릭시 params 못받아오는 문제 수정 #192
- SignUpForm.jsx: 공백 닉네임이나 공백 미믹, 공백 댓글 입력이 가능한 문제, 인증을 하지 않은 경우, 출력되는 메시지가 공통으로 발생하는 문제 수정 #222 #221
- WriteTodoForm.jsx: 공백 닉네임이나 공백 미믹, 공백 댓글 입력이 가능한 문제 수정 #221
=> Merge (revision: b4a993f)

src/components/common/ProfileCard.jsx, src/components/features/feedDetail/DetailCard.jsx, src/components/features/feedDetail/FeedDetailContainer.jsx, src/components/features/modifyProfile/ProfileModifyForm.jsx, src/components/features/signUp/SignUpForm.jsx, src/components/features/todo/WriteTodoForm.jsx
- Fix
- DetailCard.jsx: 버튼 영역칸 위치 조정
- FeedDetailContainer.jsx: 버튼 영역칸 위치 조정, trim() 관련 이슈 수정
- ProfileCard.jsx: 이미지 리사이징 이슈 관련 임시 코드 추가
- ProfileModifyForm.jsx & SignUpForm.jsx & WriteTodoForm.jsx: trim() 관련 이슈 수정
=> Merge (revision: 2141617)

src/components/common/ProfileCard.jsx, src/components/features/error/ErrorPageContainer.jsx, src/components/features/feed/FeedPageContainer.jsx, src/components/features/feedDetail/FeedDetailContainer.jsx
3c581a8
[Fix]
- ProfileCard.jsx : 다른 유저페이지 모달창에서 css정상적으로 나오지 않는 현상 수정
- ErrorPageContainer.jsx : 에러페이지 css수정
- FeedPageContainer.jsx :  정렬모달 회색영역만 클릭했을 때 모달창 닫히게 수정
- FeedDetailContainer.jsx : 모바일 환경 css 수정
7d1174b
[Fix]
- FeedDetailContainer.jsx :  모바일 css 수정
=> Merge ( revision : 3c581a8 ~ 7d1174b )

src/components/features/feedDetail/DetailCard.jsx, src/components/features/feedDetail/FeedDetailContainer.jsx, src/components/features/ohterPage/OthersCard.jsx, src/components/features/setToDo/SetUpToDoCard.jsx, src/components/features/todo/WriteTodoForm.jsx, src/components/interface/styledCommon.jsx
- Fix
- WriteTodoForm.jsx: 한글자만 입력하고 띄어쓰기를 엄청 써도 등록이 되는 문제 수정
- DetailCard.jsx & FeedDetailContainer.jsx & OthersCard.jsx & SetUpToDoCard.jsx & styledCommon.jsx: 팝업 버튼 관련 영역 수정
=> Merge (revision: 77e0c5a~ae969b8)

src/components/common/ProfileCard.jsx, src/components/features/feedDetail/FeedDetailContainer.jsx, src/components/features/modifyProfile/ProfileModifyForm.jsx
- Fix
- ProfileModifyForm.jsx: 닉네임 입력란에 저장되는 값이 이상해지는 문제 수정
- ProfileCard.jsx & FeedDetailContainer.jsx: 프로필카드에서 이미지가 정상적으로 출력되지 않는 문제 수정 #197
=> Merge (revision: 7afb03f)

package-lock.json, package.json, src/components/features/test/TestForm.jsx, src/pages/testPage.jsx
- Fix(
TestForm.jsx : 기본로직구성, 
testPage.jsx : 카카오톡공유 추가중 ,
package.json/p…ackage-lock.json : react-helmet-async 설치 - 카톡공유기능에 사용가능한지 테스트중  )
=> Merge (revision : 759a32e)

src/components/common/ProfileCard.jsx, src/components/features/feedDetail/FeedDetailContainer.jsx
Fix
- ProfileCard.jsx :  미믹 등급 개수 수정
- FeedDetailContainer.jsx : 미믹 등급 개수 수정
=> Merge ( revision : 9587678 ~ fd703c2 )

src/components/features/test/TestForm.jsx, src/utils/button.jsx
- Fix (
TestForm.jsx - Button 컴포넌트 추가), 
- Add (
button.jsx :button 컴포넌트생성 )
=> Merge (revision : 3191faa)

public/images/Challenge.svg, src/components/common/ChallengeCard.jsx, src/images/Challenge.svg
- Fix
- ChallengeCard.jsx & Challenge.jsx: hover 시 아이콘 색상 변경 되지 않는 문제 수정
- Delete
- Challenge.svg
=> Merge (revision: c0dd3e7)

src/components/features/test/TestForm.jsx
- Fix ( 
TestForm.jsx : 모바일사이즈css 적용 )
=> Merge (revision :f2d7b53)

src/components/features/test/TestForm.jsx
- Fix
- TestForm.jsx: 질문, 답변 내용 수정 및 일부 CSS 사항 수정, Progress Bar 추가
=> Merge (revision: 98e989a)

src/components/features/test/TestForm.jsx, src/layout/layout.jsx
- Fix
- TestForm.jsx: 페이지 높이 조정
- layout.jsx: 모바일 화면에서 레이아웃 내 섀도우 제거 적용
=> Merge (revision: dcf5275)

src/components/common/ProfileCard.jsx, src/components/features/feed/FeedPageContainer.jsx, src/components/features/login/LoginForm.jsx, src/components/features/myPage/LoginSelect.jsx, src/components/features/ohterPage/UserProfileContainer.jsx
Fix(ProfileCard.jsx, FeedPageContainer.jsx, LoginForm.jsx, LoginSelect.jsx, UserProfileContainer.jsx : 접근성 관련 tabIndex요소들 추가)
=> Merge(revision : 4335144 ) 

src/components/features/test/TestForm.jsx
- Fix ( 
TestForm.jsx : onClickShared 공유기능추가  )
=> Merge (revision : 00c2fc0)

src/components/common/ProfileCard.jsx, src/components/features/feed/FeedPageContainer.jsx, src/components/features/feedDetail/FeedDetailContainer.jsx, src/components/features/login/LoginForm.jsx, src/components/features/myPage/LoginSelect.jsx
Fix
- ProfileCard.jsx , FeedDetailContainer.jsx: 모바일에서 미믹등급 모달 크기 수정
- FeedPageContainer.jsx : 접근성 관련 넘겨야할 부분 수정
-LoginForm.jsx, LoginSelect.jsx : 모바일 css적용
=> Merge( revision : 4450a46 )

src/components/common/ProfileCard.jsx, src/components/features/feedDetail/FeedDetailContainer.jsx
[Fix]
- ProfileCard.jsx , FeedDetailContainer.jsx :  모바일 환경 에서 모달창 크기 수정
=> Merge ( revision : 79b5bd ~ c8e96e9 )

src/components/common/ProfileCard.jsx, src/components/features/feed/FeedPageContainer.jsx, src/components/features/todo/WriteTodoForm.jsx
Fix
-ProfileCard.jsx : 디자인 수정 요청에 따른 CSS수정  프로필카드 하단 숫자,LV부분
-FeedPageContainer.jsx : 디자인 수정 요청에 따른 CSS수정 도전완료 가리기, 최신순 글자 부분
-WriteTodoForm.jsx : 디자인 수정 요청에 따른 CSS수정 나타나는 글자 부분
=> Merge ( revision : f0d46f8 )

src/components/common/header.jsx, src/components/features/main/MainContainer.jsx, src/components/features/test/TestForm.jsx
- Fix
- header.jsx: Test 페이지일 시, Back 버튼 이동 경로를 Main으로 설정
- MainContain.jsx: 메인 화면에 TEST 버튼 영역 추가 (임시)
- TestForm.jsx: Mac 및 Android Web View 관련 공유 기능 수정, 정보 출저 추가
=> Merge (revision: 669dff0)

src/components/features/test/TestForm.jsx
Fix ( TestForm.jsx : 접근성 보이스리더 텍스트 추가 )
=> Merge (revision : 8b994a0)

src/components/features/todo/WriteTodoForm.jsx
Fix
- WriteTodoForm.jsx : 10자에서 5자로 수정
=> Merge(revision : ba99304 )
